const FirebaseConfigs = {
	API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
	AUTH_DOMAIN: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
	PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID,
	STORAGE_BUCKET: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
	MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
	APP_ID: process.env.NEXT_PUBLIC_APP_ID,
	MEASUREMENT_ID: process.env.NEXT_PUBLIC_MEASUREMENT_ID,
    FIREBASE_COLLECTION_PREFIX: process.env.NEXT_PUBLIC_FIREBASE_COLLECTION_PREFIX,
};


export { FirebaseConfigs};
